<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:07
?>
<?php

/**
 * lorfields actions.
 *
 * @package    sf_sandbox
 * @subpackage lorfields
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class lorfieldsActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('lorfields', 'list');
  }

  public function executeList()
  {
    $this->lorfieldss = LorfieldsPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->lorfields = LorfieldsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->lorfields);
  }

  public function executeCreate()
  {
    $this->lorfields = new Lorfields();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->lorfields = LorfieldsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->lorfields);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $lorfields = new Lorfields();
    }
    else
    {
      $lorfields = LorfieldsPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($lorfields);
    }

    $lorfields->setId($this->getRequestParameter('id'));
    $lorfields->setFields($this->getRequestParameter('fields'));

    $lorfields->save();

    return $this->redirect('lorfields/show?id='.$lorfields->getId());
  }

  public function executeDelete()
  {
    $lorfields = LorfieldsPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($lorfields);

    $lorfields->delete();

    return $this->redirect('lorfields/list');
  }
}
