<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 05:48:38
?>
<?php use_helper('Object') ?>

<?php echo form_tag('chaptersandevents/update') ?>

<?php echo object_input_hidden_tag($chaptersandevents, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($chaptersandevents, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Type:</th>
  <td><?php echo object_input_tag($chaptersandevents, 'getType', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($chaptersandevents->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'chaptersandevents/delete?id='.$chaptersandevents->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'chaptersandevents/show?id='.$chaptersandevents->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'chaptersandevents/list') ?>
<?php endif; ?>
</form>
