<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 05:48:38
?>
<h1>chaptersandevents</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Type</th>
</tr>
</thead>
<tbody>
<?php foreach ($chaptersandeventss as $chaptersandevents): ?>
<tr>
    <td><?php echo link_to($chaptersandevents->getId(), 'chaptersandevents/show?id='.$chaptersandevents->getId()) ?></td>
      <td><?php echo $chaptersandevents->getName() ?></td>
      <td><?php echo $chaptersandevents->getType() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'chaptersandevents/create') ?>
