<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:54:07
?>
<?php use_helper('Object') ?>

<?php echo form_tag('organizational/update') ?>

<?php echo object_input_hidden_tag($organizational, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($organizational, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($organizational->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'organizational/delete?id='.$organizational->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'organizational/show?id='.$organizational->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'organizational/list') ?>
<?php endif; ?>
</form>
