<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:54:07
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $organizational->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $organizational->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'organizational/edit?id='.$organizational->getId()) ?>
&nbsp;<?php echo link_to('list', 'organizational/list') ?>
