<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:53:33
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $careerresources->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $careerresources->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'careerresources/edit?id='.$careerresources->getId()) ?>
&nbsp;<?php echo link_to('list', 'careerresources/list') ?>
