<?php include_component('home', 'leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:30
?>
<?php use_helper('Object') ?>

<?php echo form_tag('chapterregion/update') ?>

<?php echo object_input_hidden_tag($chapterregion, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Chapter:</th>
  <td><?php echo object_select_tag($chapterregion, 'getChapterId', array (
  'related_class' => 'Chapter',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Region:</th>
  <td><?php echo object_select_tag($chapterregion, 'getRegionId', array (
  'related_class' => 'Region',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($chapterregion->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'chapterregion/delete?id='.$chapterregion->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'chapterregion/show?id='.$chapterregion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'chapterregion/list') ?>
<?php endif; ?>
</form>
