<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:20:06
?>
<?php

/**
 * userhobbies actions.
 *
 * @package    sf_sandbox
 * @subpackage userhobbies
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class userhobbiesActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('userhobbies', 'list');
  }

  public function executeList()
  {
    $this->userhobbiess = UserhobbiesPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->userhobbies = UserhobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->userhobbies);
  }

  public function executeCreate()
  {
    $this->userhobbies = new Userhobbies();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->userhobbies = UserhobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->userhobbies);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $userhobbies = new Userhobbies();
    }
    else
    {
      $userhobbies = UserhobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($userhobbies);
    }

    $userhobbies->setId($this->getRequestParameter('id'));
    $userhobbies->setUserId($this->getRequestParameter('user_id') ? $this->getRequestParameter('user_id') : null);
    $userhobbies->setHobbiesId($this->getRequestParameter('hobbies_id') ? $this->getRequestParameter('hobbies_id') : null);
    $userhobbies->setOther($this->getRequestParameter('other'));
    $userhobbies->setHobbiesflag($this->getRequestParameter('hobbiesflag'));

    $userhobbies->save();

    return $this->redirect('userhobbies/show?id='.$userhobbies->getId());
  }

  public function executeDelete()
  {
    $userhobbies = UserhobbiesPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($userhobbies);

    $userhobbies->delete();

    return $this->redirect('userhobbies/list');
  }
}
