<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 05:48:38
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $chaptersandevents->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $chaptersandevents->getName() ?></td>
</tr>
<tr>
<th>Type: </th>
<td><?php echo $chaptersandevents->getType() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'chaptersandevents/edit?id='.$chaptersandevents->getId()) ?>
&nbsp;<?php echo link_to('list', 'chaptersandevents/list') ?>
