<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:43
?>
<h1>loruser</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Lorvalues</th>
  <th>User</th>
</tr>
</thead>
<tbody>
<?php foreach ($lorusers as $loruser): ?>
<tr>
    <td><?php echo link_to($loruser->getId(), 'loruser/show?id='.$loruser->getId()) ?></td>
      <td><?php echo $loruser->getLorvaluesId() ?></td>
      <td><?php echo $loruser->getUserId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'loruser/create') ?>
