<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:43
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $loruser->getId() ?></td>
</tr>
<tr>
<th>Lorvalues: </th>
<td><?php echo $loruser->getLorvaluesId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $loruser->getUserId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'loruser/edit?id='.$loruser->getId()) ?>
&nbsp;<?php echo link_to('list', 'loruser/list') ?>
