<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:50
?>
<?php

/**
 * userchapterregion actions.
 *
 * @package    sf_sandbox
 * @subpackage userchapterregion
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class userchapterregionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('userchapterregion', 'list');
  }

  public function executeList()
  {
    $this->userchapterregions = UserchapterregionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->userchapterregion = UserchapterregionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->userchapterregion);
  }

  public function executeCreate()
  {
    $this->userchapterregion = new Userchapterregion();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->userchapterregion = UserchapterregionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->userchapterregion);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $userchapterregion = new Userchapterregion();
    }
    else
    {
      $userchapterregion = UserchapterregionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($userchapterregion);
    }

    $userchapterregion->setId($this->getRequestParameter('id'));
    $userchapterregion->setUserId($this->getRequestParameter('user_id') ? $this->getRequestParameter('user_id') : null);
    $userchapterregion->setChapterregionId($this->getRequestParameter('chapterregion_id') ? $this->getRequestParameter('chapterregion_id') : null);
    $userchapterregion->setOther($this->getRequestParameter('other'));
    $userchapterregion->setUcrflag($this->getRequestParameter('ucrflag'));

    $userchapterregion->save();

    return $this->redirect('userchapterregion/show?id='.$userchapterregion->getId());
  }

  public function executeDelete()
  {
    $userchapterregion = UserchapterregionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($userchapterregion);

    $userchapterregion->delete();

    return $this->redirect('userchapterregion/list');
  }
}
