<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:41
?>
<h1>professional</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Employer</th>
  <th>Employerflag</th>
  <th>Position</th>
  <th>Positionflag</th>
</tr>
</thead>
<tbody>
<?php foreach ($professionals as $professional): ?>
<tr>
    <td><?php echo link_to($professional->getId(), 'professional/show?id='.$professional->getId()) ?></td>
      <td><?php echo $professional->getUserId() ?></td>
      <td><?php echo $professional->getEmployer() ?></td>
      <td><?php echo $professional->getEmployerflag() ?></td>
      <td><?php echo $professional->getPosition() ?></td>
      <td><?php echo $professional->getPositionflag() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'professional/create') ?>
