<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:41
?>
<div class="page">
	<h3>Professional Details</h3>
	<div class="vspacer20">&nbsp;</div>
	<?php $col = 0;
			$dataflag = 0;
		//$professionals = $user->getProfessional();
		foreach ($professionals as $professional):
			$profflag = 0;
			if( ($professional->getEmployer() && ($professional->getEmployer() !== sfConfig::get('app_privacy_message')))){
				$profflag += 1;
			}
			if(($professional->getPosition() && ($professional->getPosition() !== sfConfig::get('app_privacy_message'))) ){
				$profflag +=2;
			}
			$proftext = '';
			switch($profflag){
				case 1: $proftext = "At <b>".$professional->getEmployer()."</b>"; $col++; $dataflag=1; break;
				case 2: $proftext = "<b>".$professional->getPosition()."</b>"; $col++; $dataflag=1; break;
				case 3: $proftext = "<b>".$professional->getPosition()."</b> at <b>".$professional->getEmployer()."</b>"; $col++; $dataflag=1; break;
			}
	?>
			<div class="<?php if($col%2==0): echo "evenRow"; else: echo "oddRow"; endif; ?>">
				<div class="vprowdata">
					<?php if($proftext): echo $proftext; endif; ?>
					<i>
						<?php if($professional->getFromdate()): echo " From ".date('jS M \'y',strtotime($professional->getFromdate())); endif; if($professional->getTodate()): echo " till ".date('jS M \'y',strtotime($professional->getTodate())); endif; ?>
					</i>
				</div>
				<div class="imgRight">					
					<a href="/professional/edit/id/<?php echo $professional->getId() ?>.html"><img src="/images/pencil.png" alt="Edit" title="Edit" style="cursor: pointer;"></a>
					<img src="/images/del2.png" alt="Delete" title="Delete" style="cursor: pointer;" onclick="delprof('<?php echo $professional->getId() ?>')">
				</div>
			</div>
			
	<?php
		endforeach;
	?>
	<?php if(!$dataflag): $col++;?>
		<div class="<?php if($col%2==0): echo "evenRow"; else: echo "oddRow"; endif; ?>">
			<div class="centermsg"><?php echo sfConfig::get('app_profile_blankSection') ?></div>
		</div>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
		<div class="formbuttons"><a href="/professional/add.html"><img src="/images/addnew.png" alt="Add" /></a></div>
	<div class="vspacer20">&nbsp;</div>
	<?php if($elors): ?>
	<div class="oddRow">
		<div class="lorhead">Comment on Employer </div>
		<div class="lorrejectall"><?php echo link_to('<img src="/images/rejectall.gif">', '/professional/lorrejectall?a=e') ?></div>
			<?php $temp = 0; 
			foreach($elors as $lor): ?>
				<?php if($temp ==0): ?>
					<div class="lorrow">
				<?php else: ?>
					<div class="lorrow1">
				<?php endif; ?> 
						<div class="smallimage">
								<?php if($lor->getPersonal()->getImage()): ?>
									<img src="<?php echo $lor->getPersonal()->getImage(); ?>" width="35px;" height="35px;">
								<?php else: ?>
									<img src="<?php echo sfConfig::get('app_profile_dummyimage') ?>" width="35px;" height="35px;">
								<?php endif; ?> 
						</div>	
						<div class="lormsg1">
							<?php echo $lor->getPersonal()->getFirstname(); ?>
						</div>
						<div class="lormsg2">
							says :
						</div>
						<div class="lorreject">
							<?php echo link_to('Reject', '/professional/lorreject?lorid='.$lor->getId()) ?>
						</div>
						<div class="lormsg3">
							<?php echo $lor->getData() ?>
						</div>
					</div>
		<?php $temp++; 
		endforeach; ?>
	</div>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
	<?php if($plors): ?>
		<div class="oddRow">
			<div class="lorhead">Comment on Position </div>
			<div class="lorrejectall"><?php echo link_to('<img src="/images/rejectall.gif">', '/professional/lorrejectall?a=p') ?></div>
				<?php $temp = 0; 
				foreach($plors as $lor): ?>
					<?php if($temp ==0): ?>
						<div class="lorrow">
					<?php else: ?>
						<div class="lorrow1">
					<?php endif; ?> 
							<div class="smallimage">
									<?php if($lor->getPersonal()->getImage()): ?>
										<img src="<?php echo $lor->getPersonal()->getImage(); ?>" width="35px;" height="35px;">
									<?php else: ?>
										<img src="<?php echo sfConfig::get('app_profile_dummyimage') ?>" width="35px;" height="35px;">
									<?php endif; ?> 
							</div>	
							<div class="lormsg1">
								<?php echo $lor->getPersonal()->getFirstname(); ?>
							</div>
							<div class="lormsg2">
								says :
							</div>
							<div class="lorreject">
								<?php echo link_to('Reject', '/professional/lorreject?lorid='.$lor->getId()) ?>
							</div>
							<div class="lormsg3">
								<?php echo $lor->getData() ?>
							</div>
						</div>
			<?php $temp++; 
			endforeach; ?>
		</div>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
</div>

<script type="text/javascript">
	function delprof(id){
		if(confirm("Are you sure!!")){
			document.location.href = "/professional/delete/id/"+id+".html";
		}
	}
</script>
