<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:52:55
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $involvement->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $involvement->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'involvement/edit?id='.$involvement->getId()) ?>
&nbsp;<?php echo link_to('list', 'involvement/list') ?>
