<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:25
?>
<h1>degree</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($degrees as $degree): ?>
<tr>
    <td><?php echo link_to($degree->getId(), 'degree/show?id='.$degree->getId()) ?></td>
      <td><?php echo $degree->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'degree/create') ?>
