<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:38
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $hobbies->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $hobbies->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'hobbies/edit?id='.$hobbies->getId()) ?>
&nbsp;<?php echo link_to('list', 'hobbies/list') ?>
