<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:38
?>
<?php use_helper('Object') ?>

<?php echo form_tag('hobbies/update') ?>

<?php echo object_input_hidden_tag($hobbies, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($hobbies, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($hobbies->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'hobbies/delete?id='.$hobbies->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'hobbies/show?id='.$hobbies->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'hobbies/list') ?>
<?php endif; ?>
</form>
