<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 07:28:59
?>
<?php include_component('home', 'leftmenu'); ?>
<?php use_helper('Object') ?>

<?php echo form_tag('peppage/update') ?>

<?php echo object_input_hidden_tag($peppage, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Tabname:</th>
  <td><?php echo object_input_tag($peppage, 'getTabname', array (
  'size' => 25,
)) ?></td>
</tr>
<tr>
  <th>Content:</th>
  <td><?php echo object_textarea_tag($peppage, 'getContent', array (
  	'rich' => 'fck',
	'height' => 295,
	'width'	=> 770,
)) ?></td>
</tr>
<tr>
  <th>Sequence:</th>
  <td><?php echo object_input_tag($peppage, 'getSequence', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($peppage->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'peppage/delete?id='.$peppage->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'peppage/mylist') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'peppage/mylist') ?>
<?php endif; ?>
</form>
