<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 07:28:59
?>
<h1>peppage</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Tabname</th>
  <th>Content</th>
  <th>Sequence</th>
</tr>
</thead>
<tbody>
<?php foreach ($peppages as $peppage): ?>
<tr>
    <td><?php echo link_to($peppage->getId(), 'peppage/show?id='.$peppage->getId()) ?></td>
      <td><?php echo $peppage->getTabname() ?></td>
      <td><?php echo $peppage->getContent() ?></td>
      <td><?php echo $peppage->getSequence() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'peppage/create') ?>
