<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 06:16:47
?>
<?php include_component('home','leftmenu'); ?>

<h1>peppage</h1>

<table>
<thead>
<tr>
  <th>Sequence</th>
  <th>Tabname</th>
  <th>Action</th>
</tr>
</thead>
<tbody>
<?php foreach ($userpages as $userpage): 
		$peppage = PeppagePeer::retrieveByPK($userpage->getPeppageId());
?>
<tr>
	  <td><?php echo $peppage->getSequence(); ?></td>
      <td><?php echo $peppage->getTabname(); ?></td>
      <td><?php echo link_to('edit', 'peppage/edit?id='.$peppage->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo button_to ('Add a Page', 'peppage/create') ?>
