<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 07:28:59
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $peppage->getId() ?></td>
</tr>
<tr>
<th>Tabname: </th>
<td><?php echo $peppage->getTabname() ?></td>
</tr>
<tr>
<th>Content: </th>
<td><?php echo $peppage->getContent() ?></td>
</tr>
<tr>
<th>Sequence: </th>
<td><?php echo $peppage->getSequence() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'peppage/edit?id='.$peppage->getId()) ?>
&nbsp;<?php echo link_to('list', 'peppage/list') ?>
