<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/02/24 11:45:46

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $validators['myfileValidator'] = new sfFileValidator();
  $validators['myfileValidator']->initialize($context, array (
  'mime_types' => 
  array (
    0 => 'text/comma-separated-values',
  ),
  'mime_types_error' => 'Only CSV files are allowed',
  'max_size' => 2048000,
  'max_size_error' => 'Upload file of size upto 2MB',
));
  $validatorManager->registerName('myfile', 1, 'Select a file', null, null, false);
  $validatorManager->registerValidator('myfile', $validators['myfileValidator'], null);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['myfileValidator'] = new sfFileValidator();
  $validators['myfileValidator']->initialize($context, array (
  'mime_types' => 
  array (
    0 => 'text/comma-separated-values',
  ),
  'mime_types_error' => 'Only CSV files are allowed',
  'max_size' => 2048000,
  'max_size_error' => 'Upload file of size upto 2MB',
));
  $validatorManager->registerName('myfile', 1, 'Select a file', null, null, false);
  $validatorManager->registerValidator('myfile', $validators['myfileValidator'], null);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
