<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/02/24 11:45:41
$this->security = array (
  'adminmenu' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'participate' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'consumer',
        1 => 'admin',
      ),
    ),
  ),
  'bulkuploadform' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'bulkupload' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
