<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:15:43
?>
<?php use_helper('Object') ?>

<?php echo form_tag('userrole/update') ?>

<?php echo object_input_hidden_tag($userrole, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($userrole, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Role:</th>
  <td><?php echo object_select_tag($userrole, 'getRoleId', array (
  'related_class' => 'Role',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($userrole->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'userrole/delete?id='.$userrole->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'userrole/show?id='.$userrole->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'userrole/list') ?>
<?php endif; ?>
</form>
