<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:22
?>
<?php use_helper('Object') ?>

<?php echo form_tag('userbadge/update') ?>

<?php echo object_input_hidden_tag($userbadge, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($userbadge, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Badge:</th>
  <td><?php echo object_select_tag($userbadge, 'getBadgeId', array (
  'related_class' => 'Badge',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Badgeflag:</th>
  <td><?php echo object_input_tag($userbadge, 'getBadgeflag', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($userbadge->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'userbadge/delete?id='.$userbadge->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'userbadge/show?id='.$userbadge->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'userbadge/list') ?>
<?php endif; ?>
</form>
