<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:41
?>
<?php use_helper('Object') ?>

<?php echo form_tag('professional/update') ?>

<?php echo object_input_hidden_tag($professional, 'getId') ?>

<input type="hidden" name="user_id" value="<?php echo $userid; ?>">

<?php include_component('home', 'messages'); ?>

<div class="page">
	<?php if($userid): ?>
		<h3>Add Employment Details</h3>
	<?php else: ?>
		<h3>Edit Employment Details</h3>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Employer :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($professional, 'getEmployer', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('employerflag', options_for_select($privacyoptions, $professional->getEmployerflag())) ?>
		</div>
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Position :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($professional, 'getPosition', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('positionflag', options_for_select($privacyoptions, $professional->getPositionflag())) ?>
		</div>	
	</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">From :</div></div>
		<div class="editrowdatamiddle">
			<?php echo object_input_date_tag($professional, 'getFromdate', array ( 'rich' => true, 'withtime' => false, 'size' => 30, 'calendar_button_img'=>'/images/calendar.png' )) ?>
			<label>(yyyy-mm-dd)</label>
		</div>
		<div class="editrowdataright">&nbsp;</div>	
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">To :</div></div>
		<div class="editrowdatamiddle">
			<?php echo object_input_date_tag($professional, 'getTodate', array ( 'rich' => true, 'withtime' => false, 'size' => 30, 'calendar_button_img'=>'/images/calendar.png' )) ?>
			<label>(yyyy-mm-dd)</label>
		</div>
		<div class="editrowdataright">&nbsp;</div>	
	</div>
		
	<div class="vspacer20">&nbsp;</div>
	<div class="formbuttons">
		<input type="image" src="/images/save.png" alt="Update" title="Save and Back to View">
		<a href="/professional/show.html">
			<img src="/images/back.png" alt="Back" title="Back to View">
		</a>
	</div>
	<div class="vspacer20">&nbsp;</div>
</div>

</form>

