<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:41
?>
<table class="showprofile">
<tbody>
<!--<tr>
<th>Id: </th>
<td><?php echo $professional->getId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $professional->getUserId() ?></td>
</tr>
-->

<tr>
<th>Employer: </th>
<td><?php echo $professional->getEmployer() ?></td>
<th>Visible to:  </th>
<td><?php if($professional->getEmployerflag() == 1): echo "None"; elseif($professional->getEmployerflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>
</tr>

<tr>
<th>Position: </th>
<td><?php echo $professional->getPosition() ?></td>
<th>Visible to: </th>
<td><?php if($professional->getPositionflag() == 1): echo "None"; elseif($professional->getPositionflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>

</tr>

</tbody>
</table>
<hr />
<?php echo link_to('edit', 'professional/edit?id='.$professional->getId()) ?>

<!--


&nbsp;<?php echo link_to('list', 'professional/list') ?>
-->