<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 06:16:16
?>
<?php use_helper('Object') ?>

<?php echo form_tag('pepuser/update') ?>

<?php echo object_input_hidden_tag($pepuser, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($pepuser, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Peppage:</th>
  <td><?php echo object_select_tag($pepuser, 'getPeppageId', array (
  'related_class' => 'Peppage',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($pepuser->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'pepuser/delete?id='.$pepuser->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'pepuser/show?id='.$pepuser->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'pepuser/list') ?>
<?php endif; ?>
</form>
