<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 06:16:17
?>
<h1>pepuser</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Peppage</th>
</tr>
</thead>
<tbody>
<?php foreach ($pepusers as $pepuser): ?>
<tr>
    <td><?php echo link_to($pepuser->getId(), 'pepuser/show?id='.$pepuser->getId()) ?></td>
      <td><?php echo $pepuser->getUserId() ?></td>
      <td><?php echo $pepuser->getPeppageId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'pepuser/create') ?>
