<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:07
?>
<?php use_helper('Object') ?>

<?php echo form_tag('lorfields/update') ?>

<?php echo object_input_hidden_tag($lorfields, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Fields:</th>
  <td><?php echo object_input_tag($lorfields, 'getFields', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($lorfields->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'lorfields/delete?id='.$lorfields->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'lorfields/show?id='.$lorfields->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'lorfields/list') ?>
<?php endif; ?>
</form>
