<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:07
?>
<h1>lorfields</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Fields</th>
</tr>
</thead>
<tbody>
<?php foreach ($lorfieldss as $lorfields): ?>
<tr>
    <td><?php echo link_to($lorfields->getId(), 'lorfields/show?id='.$lorfields->getId()) ?></td>
      <td><?php echo $lorfields->getFields() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'lorfields/create') ?>
