<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:07
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $lorfields->getId() ?></td>
</tr>
<tr>
<th>Fields: </th>
<td><?php echo $lorfields->getFields() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'lorfields/edit?id='.$lorfields->getId()) ?>
&nbsp;<?php echo link_to('list', 'lorfields/list') ?>
