<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/02/24 11:45:40

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'itbhu',
  'username' => 'root',
  'password' => 'neev',
), 'propel');
$this->databases['propel'] = $database;
