<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/02/24 11:45:40
sfConfig::add(array(
  'app_pager_homepage_max' => 10,
  'app_web_name' => 'itbhuglobal.org',
  'app_mail_server_type' => 'smtp',
  'app_mail_hostname' => 'neevtech.com',
  'app_mail_username' => 'neev-smtp',
  'app_mail_password' => 'sp2Enu',
  'app_mail_character' => 'utf-8',
  'app_from_mail' => 'system@itbhuglobal.org',
  'app_from_name' => 'ITBHUGlobal org Administrator',
  'app_to_adminmail' => 'gourishanker@neevtech.com',
));
