<?php include_component('home', 'leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:10
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $region->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $region->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'region/edit?id='.$region->getId()) ?>
&nbsp;<?php echo link_to('list', 'region/list') ?>
