<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:15:01
?>
<h1>role</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Description</th>
</tr>
</thead>
<tbody>
<?php foreach ($roles as $role): ?>
<tr>
    <td><?php echo link_to($role->getId(), 'role/show?id='.$role->getId()) ?></td>
      <td><?php echo $role->getName() ?></td>
      <td><?php echo $role->getDescription() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'role/create') ?>
