<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:50
?>
<?php use_helper('Object') ?>

<?php echo form_tag('userchapterregion/update') ?>

<?php echo object_input_hidden_tag($userchapterregion, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($userchapterregion, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Chapterregion:</th>
  <td><?php echo object_select_tag($userchapterregion, 'getChapterregionId', array (
  'related_class' => 'Chapterregion',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Other:</th>
  <td><?php echo object_input_tag($userchapterregion, 'getOther', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Ucrflag:</th>
  <td><?php echo object_input_tag($userchapterregion, 'getUcrflag', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($userchapterregion->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'userchapterregion/delete?id='.$userchapterregion->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'userchapterregion/show?id='.$userchapterregion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'userchapterregion/list') ?>
<?php endif; ?>
</form>
