<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:50
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $userchapterregion->getId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $userchapterregion->getUserId() ?></td>
</tr>
<tr>
<th>Chapterregion: </th>
<td><?php echo $userchapterregion->getChapterregionId() ?></td>
</tr>
<tr>
<th>Other: </th>
<td><?php echo $userchapterregion->getOther() ?></td>
</tr>
<tr>
<th>Ucrflag: </th>
<td><?php echo $userchapterregion->getUcrflag() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'userchapterregion/edit?id='.$userchapterregion->getId()) ?>
&nbsp;<?php echo link_to('list', 'userchapterregion/list') ?>
