<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:20:06
?>
<?php use_helper('Object') ?>

<?php echo form_tag('userhobbies/update') ?>

<?php echo object_input_hidden_tag($userhobbies, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($userhobbies, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Hobbies:</th>
  <td><?php echo object_select_tag($userhobbies, 'getHobbiesId', array (
  'related_class' => 'Hobbies',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Other:</th>
  <td><?php echo object_input_tag($userhobbies, 'getOther', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Hobbiesflag:</th>
  <td><?php echo object_input_tag($userhobbies, 'getHobbiesflag', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($userhobbies->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'userhobbies/delete?id='.$userhobbies->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'userhobbies/show?id='.$userhobbies->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'userhobbies/list') ?>
<?php endif; ?>
</form>
