<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:15:43
?>
<h1>userrole</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Role</th>
</tr>
</thead>
<tbody>
<?php foreach ($userroles as $userrole): ?>
<tr>
    <td><?php echo link_to($userrole->getId(), 'userrole/show?id='.$userrole->getId()) ?></td>
      <td><?php echo $userrole->getUserId() ?></td>
      <td><?php echo $userrole->getRoleId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'userrole/create') ?>
