<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:15:01
?>
<?php use_helper('Object') ?>

<?php echo form_tag('role/update') ?>

<?php echo object_input_hidden_tag($role, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($role, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Description:</th>
  <td><?php echo object_textarea_tag($role, 'getDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($role->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'role/delete?id='.$role->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'role/show?id='.$role->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'role/list') ?>
<?php endif; ?>
</form>
