<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:52
?>
<?php use_helper('Object') ?>

<?php echo form_tag('chapter/update') ?>

<?php echo object_input_hidden_tag($chapter, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Chapter Name:</th>
  <td><?php echo object_input_tag($chapter, 'getName', array (
  'size' => 30,
)) ?></td>
<th>Region:</th>
<td><?php echo select_tag('region', options_for_select($regionOptions) ) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($chapter->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'chapter/delete?id='.$chapter->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'chapter/show?id='.$chapter->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'chapter/list') ?>
<?php endif; ?>
</form>
