<?php include_component('home','leftmenu'); ?>
<?php
 include_component('home','leftmenu');
 include_component('home','messages');;
?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 06:44:12
?>
<h1>mag</h1>

<?php if($count<1): echo "No Mailing Groups available."; else: ?>

<table>
<thead>
<tr>
  <th>Mailinggroup</th>
  <th>Year</th>
  <th>Branch</th>
  <th>Moderatoremail</th>
  <th>Details</th>
</tr>
</thead>
<tbody>
<?php foreach ($mags as $mag): ?>
<tr>
    
      
      <td><?php echo link_to($mag->getMailinggroup(), 'mag/show?id='.$mag->getId()) ?></td>
      <td><?php echo $mag->getYear() ?></td>
      <td><?php echo $mag->getBranch() ?></td>
      <td><?php echo $mag->getModeratoremail() ?></td>
      <td><?php echo $mag->getDetails() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>
<br><br>
<?php echo link_to ('create', 'mag/create') ?>
