<?php
 include_component('home','leftmenu');
 ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 06:44:12
?>
<table>
<tbody>

<tr>
<th>Mailinggroup: </th>
<td><?php echo $mag->getMailinggroup() ?></td>
</tr>
<tr>
<th>Year: </th>
<td><?php echo $mag->getYear() ?></td>
</tr>
<tr>
<th>Branch: </th>
<td><?php echo $mag->getBranch() ?></td>
</tr>
<tr>
<th>Moderatoremail: </th>
<td><?php echo $mag->getModeratoremail() ?></td>
</tr>
<tr>
<th>Details: </th>
<td><?php echo $mag->getDetails() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php
if($mag->getUserId() == $userid)
echo link_to('edit', 'mag/edit?id='.$mag->getId()); ?>
&nbsp;<?php echo link_to('list', 'mag/list') ?>
