<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:53:53
?>
<?php

/**
 * news actions.
 *
 * @package    sf_sandbox
 * @subpackage news
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class newsActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('news', 'list');
  }

  public function executeList()
  {
    $this->newss = NewsPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->news = NewsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->news);
  }

  public function executeCreate()
  {
    $this->news = new News();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->news = NewsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->news);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $news = new News();
    }
    else
    {
      $news = NewsPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($news);
    }

    $news->setId($this->getRequestParameter('id'));
    $news->setName($this->getRequestParameter('name'));

    $news->save();

    return $this->redirect('news/show?id='.$news->getId());
  }

  public function executeDelete()
  {
    $news = NewsPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($news);

    $news->delete();

    return $this->redirect('news/list');
  }

  public function executeMonthlynewsletter(){
	
  }
  
  public function executeIitprojectnews(){
  	
  }
}
