<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:06
?>
<h1>badge</h1>

<table>
<thead>
<tr>
  <th>Name</th>
  <th>Logo</th>
</tr>
</thead>
<tbody>
<?php foreach ($badges as $badge): ?>
<tr>
      <td><?php echo $badge->getName() ?></td>
      <td><img src="<?php echo $badge->getImage() ?>" width="100px" height="100px" > </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'badge/create') ?>
