<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:06
?>
<table>
<tbody>
<tr>
<th>Name: </th>
<td><?php echo $badge->getName() ?></td>
</tr>
<tr>
<td><img src="<?php echo $badge->getImage() ?>" width="100px" height="100px" /></td> 
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'badge/edit?id='.$badge->getId()) ?>
&nbsp;<?php echo link_to('list', 'badge/list') ?>
