<?php include_component('home', 'leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:10
?>
<h1>region</h1>

<table>
<thead>
<tr>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($regions as $region): ?>
<tr>
      <td><?php echo $region->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'region/create') ?>
