<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:36
?>
<h1>branch</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($branchs as $branch): ?>
<tr>
    <td><?php echo link_to($branch->getId(), 'branch/show?id='.$branch->getId()) ?></td>
      <td><?php echo $branch->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'branch/create') ?>
