<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:27
?>
<?php use_helper('Object') ?>

<?php echo form_tag('lorvalues/update') ?>

<?php echo object_input_hidden_tag($lorvalues, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Lorfields:</th>
  <td><?php echo object_select_tag($lorvalues, 'getLorfieldsId', array (
  'related_class' => 'Lorfields',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Data:</th>
  <td><?php echo object_input_tag($lorvalues, 'getData', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($lorvalues, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($lorvalues->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'lorvalues/delete?id='.$lorvalues->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'lorvalues/show?id='.$lorvalues->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'lorvalues/list') ?>
<?php endif; ?>
</form>
