<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:08
?>
<?php use_helper('Object') ?>
<?php echo form_tag('family/update', 'multipart=true') ?>
<?php echo object_input_hidden_tag($family, 'getId') ?>
<input type="hidden" name="user_id" value="<?php echo $family->getUserId(); ?>">


<div class="page">
	<h3>Edit Profile</h3>
	<div class="vspacer20">&nbsp;</div>
	
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Date Of Marriage :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_date_tag($family, 'getDom', array ( 'rich' => true, 'withtime' => false, 'size' => 30, 'img'=>'/images/delete.png', 'readonly'=>'readonly' )) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('domflag', options_for_select($privacyoptions, $family->getDomflag())) ?>
		</div>
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Spouse Name :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($family, 'getSpousename', array ( 'size' => 30)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('spousenameflag', options_for_select($privacyoptions, $family->getSpousenameflag())) ?>
		</div>
	</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Spouse Employer :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($family, 'getSpouseemployer', array ( 'size' => 30)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('spouseemployerflag', options_for_select($privacyoptions, $family->getSpouseemployerflag())) ?>
		</div>
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Spouse Title :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($family, 'getSpousetitle', array ( 'size' => 30)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('spousetitleflag', options_for_select($privacyoptions, $family->getSpousetitleflag())) ?>
		</div>
	</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Children :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($family, 'getChildren', array ( 'size' => 30)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" alt="privacy"/>
			<?php echo select_tag('childrenflag', options_for_select($privacyoptions, $family->getChildrenflag())) ?>
		</div>
	</div>
	
	<div class="vspacer20">&nbsp;</div>
	<div class="formbuttons">
		<input type="image" src="/images/update.png" alt="Update" title="Save and Back to View">
		<a href="<?php echo '/family/show/id/'.$family->getId() ?>.html">
			<img src="/images/back.png" alt="Back" title="Back to View">
		</a>
	</div>
	<div class="vspacer20">&nbsp;</div>
</div>
</form>

<?php /*
   echo textarea_tag('itemname','',array(
	'rich' => 'fck',
	'height' => 295,
	'width'	=> 770,'class' => 'descclass'

   )); 
    $contenttext = $this->getRequestParameter('itemname');
  	if(strpos($contenttext,'<p>')>=0){

			$contenttext=str_replace('<p>','',$contenttext);
			$contenttext=str_replace('</p>','<br/>',$contenttext);
		}
    $personal->setLinkedin($contenttext);
*/ ?>
