<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:55
?>
<h1>family</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Dom</th>
  <th>Domflag</th>
  <th>Spousename</th>
  <th>Spousenameflag</th>
  <th>Spouseemployer</th>
  <th>Spouseemployerflag</th>
  <th>Spousetitle</th>
  <th>Spousetitleflag</th>
  <th>Children</th>
  <th>Childrenflag</th>
</tr>
</thead>
<tbody>
<?php foreach ($familys as $family): ?>
<tr>
    <td><?php echo link_to($family->getId(), 'family/show?id='.$family->getId()) ?></td>
      <td><?php echo $family->getUserId() ?></td>
      <td><?php echo $family->getDom() ?></td>
      <td><?php echo $family->getDomflag() ?></td>
      <td><?php echo $family->getSpousename() ?></td>
      <td><?php echo $family->getSpousenameflag() ?></td>
      <td><?php echo $family->getSpouseemployer() ?></td>
      <td><?php echo $family->getSpouseemployerflag() ?></td>
      <td><?php echo $family->getSpousetitle() ?></td>
      <td><?php echo $family->getSpousetitleflag() ?></td>
      <td><?php echo $family->getChildren() ?></td>
      <td><?php echo $family->getChildrenflag() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'family/create') ?>
