<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:55
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $family->getId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $family->getUserId() ?></td>
</tr>
<tr>
<th>Dom: </th>
<td><?php echo $family->getDom() ?></td>
</tr>
<tr>
<th>Domflag: </th>
<td><?php echo $family->getDomflag() ?></td>
</tr>
<tr>
<th>Spousename: </th>
<td><?php echo $family->getSpousename() ?></td>
</tr>
<tr>
<th>Spousenameflag: </th>
<td><?php echo $family->getSpousenameflag() ?></td>
</tr>
<tr>
<th>Spouseemployer: </th>
<td><?php echo $family->getSpouseemployer() ?></td>
</tr>
<tr>
<th>Spouseemployerflag: </th>
<td><?php echo $family->getSpouseemployerflag() ?></td>
</tr>
<tr>
<th>Spousetitle: </th>
<td><?php echo $family->getSpousetitle() ?></td>
</tr>
<tr>
<th>Spousetitleflag: </th>
<td><?php echo $family->getSpousetitleflag() ?></td>
</tr>
<tr>
<th>Children: </th>
<td><?php echo $family->getChildren() ?></td>
</tr>
<tr>
<th>Childrenflag: </th>
<td><?php echo $family->getChildrenflag() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'family/edit?id='.$family->getId()) ?>
&nbsp;<?php echo link_to('list', 'family/list') ?>
