<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:08
?>
<div class="page">	
	<h3>Family Details</h3>	
	
	<div class="oddRow">
		<div class="rowdataleft"><div class="rowdatalefttext">Date of Marriage :</div></div>
		<div class="rowdatamiddle"><?php echo $family->getDom();date('jS F Y', $family->getDom())?></div>
		<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$family->getDomflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$family->getDomflag()) ?>"></div>
	</div>
	<div class="evenRow">
		<div class="rowdataleft"><div class="rowdatalefttext">Spouse Name :</div></div>
		<div class="rowdatamiddle"><?php echo $family->getSpousename() ?></div>
		<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$family->getSpousenameFlag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$family->getSpousenameFlag()) ?>"></div>
	</div>
	<div class="oddRow">
		<div class="rowdataleft"><div class="rowdatalefttext">Spouse Employer :</div></div>
		<div class="rowdatamiddle"><?php echo $family->getSpouseemployer() ?></div>
		<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$family->getSpouseemployerFlag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$family->getSpouseemployerFlag()) ?>"></div>
	</div>
	<div class="evenRow">
		<div class="rowdataleft"><div class="rowdatalefttext">Spouse Title :</div></div>
		<div class="rowdatamiddle"><?php echo $family->getSpousetitle()?></div>
		<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$family->getSpousetitleFlag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$family->getSpousetitleFlag()) ?>"></div>
	</div>
	<div class="oddRow">
		<div class="rowdataleft"><div class="rowdatalefttext">Childrens :</div></div>
		<div class="rowdatamiddle"><?php echo $family->getChildren() ?></div>
		<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$family->getChildrenFlag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$family->getChildrenFlag()) ?>"></div>
	</div>
	<div class="vspacer20">&nbsp;</div>
	<div class="formbuttons">
		<a href="/family/edit/id/<?php echo $family->getId(); ?>.html"><img src="/images/edit2.png" alt="Edit" title="Click here to edit your contact details"></a>
	</div>
	<div class="vspacer20">&nbsp;</div>
</div>

<div class="vspacer20">&nbsp;</div>
