<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:53:53
?>
<h1>news</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($newss as $news): ?>
<tr>
    <td><?php echo link_to($news->getId(), 'news/show?id='.$news->getId()) ?></td>
      <td><?php echo $news->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'news/create') ?>
