<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:27
?>
<?php

/**
 * lorvalues actions.
 *
 * @package    sf_sandbox
 * @subpackage lorvalues
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class lorvaluesActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('lorvalues', 'list');
  }

  public function executeList()
  {
    $this->lorvaluess = LorvaluesPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->lorvalues = LorvaluesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->lorvalues);
  }

  public function executeCreate()
  {
    $this->lorvalues = new Lorvalues();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->lorvalues = LorvaluesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->lorvalues);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $lorvalues = new Lorvalues();
    }
    else
    {
      $lorvalues = LorvaluesPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($lorvalues);
    }

    $lorvalues->setId($this->getRequestParameter('id'));
    $lorvalues->setLorfieldsId($this->getRequestParameter('lorfields_id') ? $this->getRequestParameter('lorfields_id') : null);
    $lorvalues->setData($this->getRequestParameter('data'));
    $lorvalues->setUserId($this->getRequestParameter('user_id') ? $this->getRequestParameter('user_id') : null);

    $lorvalues->save();

    return $this->redirect('lorvalues/show?id='.$lorvalues->getId());
  }

  public function executeDelete()
  {
    $lorvalues = LorvaluesPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($lorvalues);

    $lorvalues->delete();

    return $this->redirect('lorvalues/list');
  }
}
