<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:54:07
?>
<?php

/**
 * organizational actions.
 *
 * @package    sf_sandbox
 * @subpackage organizational
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class organizationalActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('organizational', 'list');
  }

  public function executeList()
  {
    $this->organizationals = OrganizationalPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->organizational = OrganizationalPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->organizational);
  }

  public function executeCreate()
  {
    $this->organizational = new Organizational();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->organizational = OrganizationalPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->organizational);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $organizational = new Organizational();
    }
    else
    {
      $organizational = OrganizationalPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($organizational);
    }

    $organizational->setId($this->getRequestParameter('id'));
    $organizational->setName($this->getRequestParameter('name'));

    $organizational->save();

    return $this->redirect('organizational/show?id='.$organizational->getId());
  }

  public function executeDelete()
  {
    $organizational = OrganizationalPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($organizational);

    $organizational->delete();

    return $this->redirect('organizational/list');
  }

  public function executeBoardofdirectors(){
  	
  }
  public function executeAboutiitbhuglobal(){
  	
  }
  public function executeBylaws(){
  	
  }
  public function executeCouncil(){
  	
  }
  
}
