<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:22
?>
<h1>userbadge</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Badge</th>
  <th>Badgeflag</th>
</tr>
</thead>
<tbody>
<?php foreach ($userbadges as $userbadge): ?>
<tr>
    <td><?php echo link_to($userbadge->getId(), 'userbadge/show?id='.$userbadge->getId()) ?></td>
      <td><?php echo $userbadge->getUserId() ?></td>
      <td><?php echo $userbadge->getBadgeId() ?></td>
      <td><?php echo $userbadge->getBadgeflag() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'userbadge/create') ?>
