<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:12
?>
<?php use_helper('Object') ?>
<?php echo form_tag('academic/update') ?>
<?php echo object_input_hidden_tag($academic, 'getId') ?>

<div class="page">
	<?php if($academic->getId()): ?>
		<h3>Edit Academic Details</h3>
	<?php else: ?>
		<h3>Add Academic Details</h3>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Degree :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($academic, 'getDegree', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" /><?php echo select_tag('degreeflag', options_for_select($privacyoptions, $academic->getDegreeflag())) ?>
		</div>
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Year :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($academic, 'getYear', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" /><?php echo select_tag('yearflag', options_for_select($privacyoptions, $academic->getYearflag())) ?>
		</div>
	</div>
	<div class="oddRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Department :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($academic, 'getDepartment', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" /><?php echo select_tag('departmentflag', options_for_select($privacyoptions, $academic->getDepartmentflag())) ?>
		</div>
	</div>
	<div class="evenRow">
		<div class="editrowdataleft"><div class="editrowdatalefttext">Institute :</div></div>
		<div class="editrowdatamiddle"><?php echo object_input_tag($academic, 'getInstitute', array ('size' => 30,)) ?></div>
		<div class="editrowdataright">
			<img src="/images/privacy.png" /><?php echo select_tag('instituteflag', options_for_select($privacyoptions, $academic->getInstituteflag())) ?>
		</div>
	</div>
	<div class="vspacer20">&nbsp;</div>
	<div class="formbuttons">
		<input type="image" src="/images/save.png" alt="save">
		<a href="/academic/show.html"><img src="/images/back.png" alt="back"></a>
	</div>
	<div class="vspacer20">&nbsp;</div>
</div>
</form>
