<?php 
	include_component('home','leftmenu');
	include_component('home', 'messages');
?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:12
?>
<div class="page">
<?php echo $ccc ?>
	<h3>Academic Details</h3>
	<div class="vspacer20">&nbsp;</div>
	<?php if($academics): ?>
		<div class="oddRow">
			<div class="acadCol1"><b>Year</b></div>
			<div class="acadCol2"><b>Degree</b></div>
			<div class="acadCol3"><b>Branch</b></div>
			<div class="acadCol4"><b>Institute</b></div>
		</div>
		<?php $i=1; foreach ($academics as $academic): $i++;?>
			<div class="<?php if($i%2 == 0): echo 'evenRow'; else: echo 'oddRow'; endif; ?>">
				<div class="acadCol1" title="<?php echo sfConfig::get('app_privacytitle_'.$academic->getYearflag()); ?>"><?php echo $academic->getYear() ?></div>
				<div class="acadCol2" title="<?php echo sfConfig::get('app_privacytitle_'.$academic->getDegreeflag()); ?>"><?php echo $academic->getDegree() ?></div>
				<div class="acadCol3" title="<?php echo sfConfig::get('app_privacytitle_'.$academic->getDepartmentflag()); ?>"><?php echo $academic->getDepartment() ?></div>
				<div class="acadCol4" title="<?php echo sfConfig::get('app_privacytitle_'.$academic->getInstituteflag()); ?>"><?php echo $academic->getInstitute() ?></div>
				<div class="acadCol5">
					<a href="/academic/edit/id/<?php echo $academic->getId() ?>.html"><img src="/images/pencil.png" alt="edit" title="edit"></a>
					<a href="#"><img src="/images/del2.png" alt="Delete" title="Delete"></a>
				</div>
			</div><a href="academic/edit/id/<?php echo $academic->getId(); ?>"> </a>
		<?php endforeach; ?>
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
		<div class="formbuttons">
			<a href="/academic/add.html"><img src="/images/addnew.png"></a>
		</div>
	<div class="vspacer20">&nbsp;</div>
	<div class="centermsg"><b>My IT BHU Badges</b></div>
	<div class="vspacer10">&nbsp;</div>
	<?php if($userbadges): ?>
	<div class="oddRow">
		<?php foreach ($userbadges as $ubadge){ ?>
				<div class="centermsg">
					<?php echo $ubadge->getBadge()->getName(); ?>
					<a href="/academic/deletebadge/id/<?php echo $ubadge->getBadgeId(); ?>.html">
						<img src="/images/del2.png" alt="delete" title="Remove this badge from the profile." width="10px" height="10px">
					</a>
				</div>
		<?php }	?>
	</div>
	<?php else: ?>
		<div class="oddRow"> 
			<div class="centermsg">No Badges.</div>
		</div>
	<?php endif; ?>
	<div class="formbuttons" style=" margin-top:10px;">
		<form name="getbadge" method="post" action="/academic/getbadge.html">
			<span style="float: left; margin-left:300px; padding-top: 3px; margin-right: 10px;"><?php echo select_tag('newbadge', options_for_select($badgelist)); ?></span>
			<div  style="float:left;"><input type="image" src="/images/getbadge.png" alt="get badge" title="Add selected badge to my profile"></div>
		</form>
	</div>
	<div class="vspacer20">&nbsp;</div>
</div>
