<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:12
?>
<table class="showprofile">
<tbody>
<!--<tr>
<th>Id: </th>
<td><?php echo $academic->getId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $academic->getUserId() ?></td>
</tr>
--><tr>

<th>Degree: </th>
<td><?php echo $academic->getDegree() ?></td>

<th>Visible to: </th>
<td><?php if($academic->getDegreeflag() == 1): echo "None"; elseif($academic->getDegreeflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>

</tr>

<tr>
<th>Year: </th>
<td><?php echo $academic->getYear() ?></td>


<th>Visible to: </th>
<td><?php if($academic->getYearflag() == 1): echo "None"; elseif($academic->getYearflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>

</tr>

<tr>
<th>Department: </th>
<td><?php echo $academic->getDepartment() ?></td>

<th>Visible to: </th>
<td><?php if($academic->getDepartmentflag() == 1): echo "None"; elseif($academic->getDepartmentflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>


</tr>

<tr>
<th>Major: </th>
<td><?php echo $academic->getMajor() ?></td>
<th>Visible to: </th>
<td><?php if($academic->getMajorflag() == 1): echo "None"; elseif($academic->getMajorflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>


</tr>

<tr>
<th>Institute: </th>
<td><?php echo $academic->getInstitute() ?></td>

<th>Visible to: </th>
<td><?php if($academic->getInstituteflag() == 1): echo "None"; elseif($academic->getInstituteflag() == 2): echo "My Classmates"; else: echo "All"; endif; ?></td>

</tr>

</tbody>
</table>
<hr />
<?php echo link_to('edit', 'academic/edit?id='.$academic->getId()) ?>
<!--

&nbsp;<?php echo link_to('list', 'academic/list') ?>
-->