<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 05:48:38
?>
<?php

/**
 * chaptersandevents actions.
 *
 * @package    sf_sandbox
 * @subpackage chaptersandevents
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class chaptersandeventsActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('chaptersandevents', 'list');
  }

  public function executeList()
  {
    $this->chaptersandeventss = ChaptersandeventsPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->chaptersandevents = ChaptersandeventsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->chaptersandevents);
  }

  public function executeCreate()
  {
    $this->chaptersandevents = new Chaptersandevents();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->chaptersandevents = ChaptersandeventsPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->chaptersandevents);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $chaptersandevents = new Chaptersandevents();
    }
    else
    {
      $chaptersandevents = ChaptersandeventsPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($chaptersandevents);
    }

    $chaptersandevents->setId($this->getRequestParameter('id'));
    $chaptersandevents->setName($this->getRequestParameter('name'));
    $chaptersandevents->setType($this->getRequestParameter('type'));

    $chaptersandevents->save();

    return $this->redirect('chaptersandevents/show?id='.$chaptersandevents->getId());
  }

  public function executeDelete()
  {
    $chaptersandevents = ChaptersandeventsPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($chaptersandevents);

    $chaptersandevents->delete();

    return $this->redirect('chaptersandevents/list');
  }
  
  
  public function executeAlumnichapters(){
  	
  }
  
  public function executeUpcommingevents(){
  	
  }
  
  public function executePhotogallery(){
  	
  }
  
  public function executeReunions(){
  	
  }
}
