<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:15:01
?>
<?php

/**
 * role actions.
 *
 * @package    sf_sandbox
 * @subpackage role
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class roleActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('role', 'list');
  }

  public function executeList()
  {
    $this->roles = RolePeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->role = RolePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->role);
  }

  public function executeCreate()
  {
    $this->role = new Role();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->role = RolePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->role);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $role = new Role();
    }
    else
    {
      $role = RolePeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($role);
    }

    $role->setId($this->getRequestParameter('id'));
    $role->setName($this->getRequestParameter('name'));
    $role->setDescription($this->getRequestParameter('description'));

    $role->save();

    return $this->redirect('role/show?id='.$role->getId());
  }

  public function executeDelete()
  {
    $role = RolePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($role);

    $role->delete();

    return $this->redirect('role/list');
  }
}
