<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:20:06
?>
<h1>userhobbies</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Hobbies</th>
  <th>Other</th>
  <th>Hobbiesflag</th>
</tr>
</thead>
<tbody>
<?php foreach ($userhobbiess as $userhobbies): ?>
<tr>
    <td><?php echo link_to($userhobbies->getId(), 'userhobbies/show?id='.$userhobbies->getId()) ?></td>
      <td><?php echo $userhobbies->getUserId() ?></td>
      <td><?php echo $userhobbies->getHobbiesId() ?></td>
      <td><?php echo $userhobbies->getOther() ?></td>
      <td><?php echo $userhobbies->getHobbiesflag() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'userhobbies/create') ?>
