<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:27
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $lorvalues->getId() ?></td>
</tr>
<tr>
<th>Lorfields: </th>
<td><?php echo $lorvalues->getLorfieldsId() ?></td>
</tr>
<tr>
<th>Data: </th>
<td><?php echo $lorvalues->getData() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $lorvalues->getUserId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'lorvalues/edit?id='.$lorvalues->getId()) ?>
&nbsp;<?php echo link_to('list', 'lorvalues/list') ?>
