<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:36
?>
<?php use_helper('Object') ?>

<?php echo form_tag('branch/update') ?>

<?php echo object_input_hidden_tag($branch, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($branch, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($branch->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'branch/delete?id='.$branch->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'branch/show?id='.$branch->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'branch/list') ?>
<?php endif; ?>
</form>
