<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:36
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $branch->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $branch->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'branch/edit?id='.$branch->getId()) ?>
&nbsp;<?php echo link_to('list', 'branch/list') ?>
