<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:14:41
?>
<?php use_helper('Object') ?>

<?php echo form_tag('user/update') ?>

<?php echo object_input_hidden_tag($user, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Username:</th>
  <td><?php echo object_input_tag($user, 'getUsername', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Password:</th>
  <td><?php echo object_input_tag($user, 'getPassword', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Enrolment:</th>
  <td><?php echo object_input_tag($user, 'getEnrolment', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Enrolflag:</th>
  <td><?php echo object_input_tag($user, 'getEnrolflag', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Roll:</th>
  <td><?php echo object_input_tag($user, 'getRoll', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Rollflag:</th>
  <td><?php echo object_input_tag($user, 'getRollflag', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Graduationyear:</th>
  <td><?php echo object_input_tag($user, 'getGraduationyear', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Graduationyearflag:</th>
  <td><?php echo object_input_tag($user, 'getGraduationyearflag', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Branch:</th>
  <td><?php echo object_select_tag($user, 'getBranchId', array (
  'related_class' => 'Branch',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Branchflag:</th>
  <td><?php echo object_input_tag($user, 'getBranchflag', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Degree:</th>
  <td><?php echo object_select_tag($user, 'getDegreeId', array (
  'related_class' => 'Degree',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Degreeflag:</th>
  <td><?php echo object_input_tag($user, 'getDegreeflag', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Secretquestion:</th>
  <td><?php echo object_input_tag($user, 'getSecretquestion', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Secretanswer:</th>
  <td><?php echo object_input_tag($user, 'getSecretanswer', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Islocked:</th>
  <td><?php echo object_checkbox_tag($user, 'getIslocked', array (
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($user->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'user/delete?id='.$user->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'user/show?id='.$user->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'user/list') ?>
<?php endif; ?>
</form>
