<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:14:41
?>
<h1>user</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Username</th>
  <th>Password</th>
  <th>Enrolment</th>
  <th>Enrolflag</th>
  <th>Roll</th>
  <th>Rollflag</th>
  <th>Graduationyear</th>
  <th>Graduationyearflag</th>
  <th>Branch</th>
  <th>Branchflag</th>
  <th>Degree</th>
  <th>Degreeflag</th>
  <th>Secretquestion</th>
  <th>Secretanswer</th>
  <th>Islocked</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
    <td><?php echo link_to($user->getId(), 'user/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getUsername() ?></td>
      <td><?php echo $user->getPassword() ?></td>
      <td><?php echo $user->getEnrolment() ?></td>
      <td><?php echo $user->getEnrolflag() ?></td>
      <td><?php echo $user->getRoll() ?></td>
      <td><?php echo $user->getRollflag() ?></td>
      <td><?php echo $user->getGraduationyear() ?></td>
      <td><?php echo $user->getGraduationyearflag() ?></td>
      <td><?php echo $user->getBranchId() ?></td>
      <td><?php echo $user->getBranchflag() ?></td>
      <td><?php echo $user->getDegreeId() ?></td>
      <td><?php echo $user->getDegreeflag() ?></td>
      <td><?php echo $user->getSecretquestion() ?></td>
      <td><?php echo $user->getSecretanswer() ?></td>
      <td><?php echo $user->getIslocked() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'user/create') ?>
