<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:14:41
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Username: </th>
<td><?php echo $user->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $user->getPassword() ?></td>
</tr>
<tr>
<th>Enrolment: </th>
<td><?php echo $user->getEnrolment() ?></td>
</tr>
<tr>
<th>Enrolflag: </th>
<td><?php echo $user->getEnrolflag() ?></td>
</tr>
<tr>
<th>Roll: </th>
<td><?php echo $user->getRoll() ?></td>
</tr>
<tr>
<th>Rollflag: </th>
<td><?php echo $user->getRollflag() ?></td>
</tr>
<tr>
<th>Graduationyear: </th>
<td><?php echo $user->getGraduationyear() ?></td>
</tr>
<tr>
<th>Graduationyearflag: </th>
<td><?php echo $user->getGraduationyearflag() ?></td>
</tr>
<tr>
<th>Branch: </th>
<td><?php echo $user->getBranchId() ?></td>
</tr>
<tr>
<th>Branchflag: </th>
<td><?php echo $user->getBranchflag() ?></td>
</tr>
<tr>
<th>Degree: </th>
<td><?php echo $user->getDegreeId() ?></td>
</tr>
<tr>
<th>Degreeflag: </th>
<td><?php echo $user->getDegreeflag() ?></td>
</tr>
<tr>
<th>Secretquestion: </th>
<td><?php echo $user->getSecretquestion() ?></td>
</tr>
<tr>
<th>Secretanswer: </th>
<td><?php echo $user->getSecretanswer() ?></td>
</tr>
<tr>
<th>Islocked: </th>
<td><?php echo $user->getIslocked() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user/list') ?>
