<?php include_component('home', 'leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:30
?>
<h1>chapterregion</h1>

<table>
<thead>
<tr>
  <th>Chapter</th>
  <th>Region</th>
</tr>
</thead>
<tbody>
<?php foreach ($chapterregions as $chapterregion): ?>
<tr>
      <td><?php echo $chapterregion->getChapter()->getName() ?></td>
      <td><?php echo $chapterregion->getRegion()->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'chapterregion/create') ?>
