<?php
// auto-generated by sfPropelCrud
// date: 2009/03/16 02:49:43
?>
<?php

/**
 * loruser actions.
 *
 * @package    sf_sandbox
 * @subpackage loruser
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class loruserActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('loruser', 'list');
  }

  public function executeList()
  {
    $this->lorusers = LoruserPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->loruser = LoruserPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->loruser);
  }

  public function executeCreate()
  {
    $this->loruser = new Loruser();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->loruser = LoruserPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->loruser);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $loruser = new Loruser();
    }
    else
    {
      $loruser = LoruserPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($loruser);
    }

    $loruser->setId($this->getRequestParameter('id'));
    $loruser->setLorvaluesId($this->getRequestParameter('lorvalues_id') ? $this->getRequestParameter('lorvalues_id') : null);
    $loruser->setUserId($this->getRequestParameter('user_id') ? $this->getRequestParameter('user_id') : null);

    $loruser->save();

    return $this->redirect('loruser/show?id='.$loruser->getId());
  }

  public function executeDelete()
  {
    $loruser = LoruserPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($loruser);

    $loruser->delete();

    return $this->redirect('loruser/list');
  }
}
