<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:53:33
?>
<?php use_helper('Object') ?>

<?php echo form_tag('careerresources/update') ?>

<?php echo object_input_hidden_tag($careerresources, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($careerresources, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($careerresources->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'careerresources/delete?id='.$careerresources->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'careerresources/show?id='.$careerresources->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'careerresources/list') ?>
<?php endif; ?>
</form>
