<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:25
?>
<?php

/**
 * degree actions.
 *
 * @package    sf_sandbox
 * @subpackage degree
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class degreeActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('degree', 'list');
  }

  public function executeList()
  {
    $this->degrees = DegreePeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->degree = DegreePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->degree);
  }

  public function executeCreate()
  {
    $this->degree = new Degree();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->degree = DegreePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->degree);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $degree = new Degree();
    }
    else
    {
      $degree = DegreePeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($degree);
    }

    $degree->setId($this->getRequestParameter('id'));
    $degree->setName($this->getRequestParameter('name'));

    $degree->save();

    return $this->redirect('degree/show?id='.$degree->getId());
  }

  public function executeDelete()
  {
    $degree = DegreePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($degree);

    $degree->delete();

    return $this->redirect('degree/list');
  }
}
