<?php include_component('home','leftmenu'); ?>
<?php
 include_component('home','leftmenu');
 include_component('home','messages');;
?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 06:44:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('mag/update') ?>

<?php echo object_input_hidden_tag($mag, 'getId') ?>

<table>
<tbody>

<tr>
  <th>Mailinggroup:</th>
  <td><?php echo object_input_tag($mag, 'getMailinggroup', array (
  'size' => '40px',
)) ?></td>
</tr>
<tr>
  <th>Year:</th>
  <td><?php echo select_tag('year', options_for_select($yearoptions) ) ?></td>
</tr>
<tr>
  <th>Branch:</th>
  <td><?php echo select_tag('branch', options_for_select($branchOptions)) ?></td>
</tr>
<tr>
  <th>Moderatoremail:</th>
  <td><?php echo object_input_tag($mag, 'getModeratoremail', array (
  'size' => '40px',
)) ?></td>
</tr>
<tr>
  <th>Details:</th>
  <td><?php echo object_textarea_tag($mag, 'getDetails', array (
  'rows' => 5,
  'cols' => 30,
))?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mag->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'mag/delete?id='.$mag->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'mag/show?id='.$mag->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'mag/list') ?>
<?php endif; ?>
</form>
