<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:21
?>
<?php use_helper('Object') ?>

<?php echo form_tag('address/update') ?>

<?php echo object_input_hidden_tag($address, 'getId') ?>


<table>
<tbody>
<!--<tr>
  <th>User:</th>
  <td><?php echo object_select_tag($address, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
-->

<tr class="oddRow">
  <th>Address:</th>
  <td><?php echo object_input_tag($address, 'getAddress', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('addressflag', options_for_select($privacyoptions, $address->getAddressflag())) ?>
</td>
</tr>

<tr class="evenRow">
  <th>City:</th>
  <td><?php echo object_input_tag($address, 'getCity', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('cityflag', options_for_select($privacyoptions, $address->getCityflag())) ?>
</td>
</tr>

<tr class="oddRow">
  <th>State:</th>
  <td><?php echo object_input_tag($address, 'getState', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('stateflag', options_for_select($privacyoptions, $address->getStateflag())) ?>
</td>

</tr>

<tr class="evenRow">
  <th>Country:</th>
  <td><?php echo object_input_tag($address, 'getCountry', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('countryflag', options_for_select($privacyoptions, $address->getCountryflag())) ?>
</td>
</tr>

<tr class="oddRow">
  <th>Postalcode:</th>
  <td><?php echo object_input_tag($address, 'getPostalcode', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('postalcodeflag', options_for_select($privacyoptions, $address->getPostalcodeflag())) ?>
</td>
</tr>

<tr class="evenRow">
  <th>Phone1:</th>
  <td><?php echo object_input_tag($address, 'getPhone1', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('phone1flag', options_for_select($privacyoptions, $address->getPhone1flag())) ?>
</td>
</tr>

<tr class="oddRow">
  <th>Phone2:</th>
  <td><?php echo object_input_tag($address, 'getPhone2', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('phone2flag', options_for_select($privacyoptions, $address->getPhone2flag())) ?>
</td>

</tr>

<tr class="evenRow">
  <th>Cellphone:</th>
  <td><?php echo object_input_tag($address, 'getCellphone', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('cellphoneflag', options_for_select($privacyoptions, $address->getCellphoneflag())) ?>
</td>
</tr>

<tr class="oddRow">
  <th>Fax:</th>
  <td><?php echo object_input_tag($address, 'getFax', array (
  'size' => 30,
)) ?></td>

<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('faxflag', options_for_select($privacyoptions, $address->getFaxflag())) ?>
</td>

</tr>

<tr class="evenRow">
  <th>Type:</th>
  <td><?php echo object_input_tag($address, 'getType', array (
  'size' => 30,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($address->getId()): ?>
 &nbsp;<?php echo button_to('Cancel', 'address/show?id='.$address->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo button_to('cancel', 'address/list') ?>
<?php endif; ?>
  
  
</form>
