<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:21
?>
<h1>address</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Address</th>
  <th>Addressflag</th>
  <th>City</th>
  <th>Cityflag</th>
  <th>State</th>
  <th>Stateflag</th>
  <th>Country</th>
  <th>Countryflag</th>
  <th>Postalcode</th>
  <th>Postalcodeflag</th>
  <th>Phone1</th>
  <th>Phone1flag</th>
  <th>Phone2</th>
  <th>Phone2flag</th>
  <th>Cellphone</th>
  <th>Cellphoneflag</th>
  <th>Fax</th>
  <th>Faxflag</th>
  <th>Type</th>
</tr>
</thead>
<tbody>
<?php foreach ($addresss as $address): ?>
<tr>
    <td><?php echo link_to($address->getId(), 'address/show?id='.$address->getId()) ?></td>
      <td><?php echo $address->getUserId() ?></td>
      <td><?php echo $address->getAddress() ?></td>
      <td><?php echo $address->getAddressflag() ?></td>
      <td><?php echo $address->getCity() ?></td>
      <td><?php echo $address->getCityflag() ?></td>
      <td><?php echo $address->getState() ?></td>
      <td><?php echo $address->getStateflag() ?></td>
      <td><?php echo $address->getCountry() ?></td>
      <td><?php echo $address->getCountryflag() ?></td>
      <td><?php echo $address->getPostalcode() ?></td>
      <td><?php echo $address->getPostalcodeflag() ?></td>
      <td><?php echo $address->getPhone1() ?></td>
      <td><?php echo $address->getPhone1flag() ?></td>
      <td><?php echo $address->getPhone2() ?></td>
      <td><?php echo $address->getPhone2flag() ?></td>
      <td><?php echo $address->getCellphone() ?></td>
      <td><?php echo $address->getCellphoneflag() ?></td>
      <td><?php echo $address->getFax() ?></td>
      <td><?php echo $address->getFaxflag() ?></td>
      <td><?php echo $address->getType() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'address/create') ?>
