<?php include_component('home','leftmenu'); ?>
<?php include_component('home','messages'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:21
?>
<div class="page">
	<h3>Contact Details</h3>
	<div class="vspacer20">&nbsp;</div>
	<input type="hidden" id="curadd" value="home">
	<div class="addressheader">
		<ul>
			<li id="homeh" style="background-color: #D5DEFB;" onclick="addview('home')">Home</li>
			<li id="workh" onclick="addview('work')">Work</li>
			<li id="permh" onclick="addview('perm')">Permanent</li>
		</ul>
	</div>

	<?php if($addressh): ?>
	<div class="addressdetail" id="home">
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Street Address :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getAddress() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getAddressflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getAddressflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">City :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getCity() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getCityflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getCityflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">State :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getState() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getStateflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getStateflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Country :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getCountryname($addressh->getCountry()) ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getCountryflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getCountryflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Postal Code :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getPostalcode() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getPostalcodeflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getPostalcodeflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 1 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getPhone1() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getPhone1flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getPhone1flag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 2 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getPhone2() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getPhone2flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getPhone2flag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Cellphone :</div></div>
			<div class="rowdatamiddle"><?php echo $addressh->getCellphone() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressh->getCellphoneflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressh->getCellphoneflag()) ?>"></div>
		</div>
	</div>
	<?php else: ?>
		<div class="oddRow">
			<div class="centermsg">Home Address not Specified</div>
		</div>	
	<?php endif; ?>

	<?php if($addressw): ?>
	<div class="addressdetail" id="work" style="display: none;">
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Street Address :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getAddress() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getAddressflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getAddressflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">City :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getCity() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getCityflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getCityflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">State :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getState() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getStateflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getStateflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Country :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getCountryname($addressw->getCountry()) ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getCountryflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getCountryflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Postal Code :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getPostalcode() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getPostalcodeflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getPostalcodeflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 1 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getPhone1() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getPhone1flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getPhone1flag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 2 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getPhone2() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getPhone2flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getPhone2flag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Cellphone :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getCellphone() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getCellphoneflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getCellphoneflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Fax :</div></div>
			<div class="rowdatamiddle"><?php echo $addressw->getFax() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressw->getFaxflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressw->getFaxflag()) ?>"></div>
		</div>
	</div>
	<?php else: ?>
		<div class="oddRow">
			<div class="centermsg">Work Address not Specified</div>
		</div>	
	<?php endif; ?>

	<?php if($addressp): ?>
	<div class="addressdetail" id="perm" style="display: none;">
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Street Address :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getAddress() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getAddressflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getAddressflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">City :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getCity() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getCityflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getCityflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">State :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getState() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getStateflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getStateflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Country :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getCountryname($addressp->getCountry()) ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getCountryflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getCountryflag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Postal Code :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getPostalcode() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getPostalcodeflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getPostalcodeflag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 1 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getPhone1() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getPhone1flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getPhone1flag()) ?>"></div>
		</div>
		<div class="oddRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Phone 2 :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getPhone2() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getPhone2flag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getPhone2flag()) ?>"></div>
		</div>
		<div class="evenRow">
			<div class="rowdataleft"><div class="rowdatalefttext">Cellphone :</div></div>
			<div class="rowdatamiddle"><?php echo $addressp->getCellphone() ?></div>
			<div class="rowdataright"><img title="<?php echo sfConfig::get('app_privacytitle_'.$addressp->getCellphoneflag()) ?>" src="/images/<?php echo sfConfig::get('app_privacyicon_'.$addressp->getCellphoneflag()) ?>"></div>
		</div>
	</div>
	<?php else: ?>
		<div class="oddRow">
			<div class="centermsg">Permanent Address not Specified</div>
		</div>	
	<?php endif; ?>
	<div class="vspacer20">&nbsp;</div>
	<div class="formbuttons">
		<a href="/address/edit/id/<?php echo $userid; ?>.html"><img src="/images/edit2.png" alt="Edit" title="Click here to edit your contact details"></a>
	</div>
	<div class="vspacer20">&nbsp;</div>

	<div class="addressheader">
		<ul>
			<li style="background-color: #D5DEFB; cursor: default;" >Chapters</li>
		</ul>
	</div>
	<div class="oddRow">
		<div class="centermsg">
			<?php     
				foreach ($ucrs as $ucr){
			    		echo $ucr->getChapterregion()->getChapter()->getName()." ";
			    		echo "<img src='/images/del2.png' width='10px' height='10px' onclick=\"delchap('".$ucr->getChapterregionId()."', '".$ucr->getChapterregion()->getChapter()->getName()."')\" style='cursor:pointer;'>&nbsp;&nbsp;&nbsp;&nbsp;";
    			}
    		?>
    	</div>
	</div>
	<div class="evenRow">
		<div class="centermsg">
			<form method="post" action="/address/joinchapter.html">
				<?php echo "Join a Chapter : ".select_tag('region', options_for_select($regionlist), array('onchange'=>'getchapters(this.value)')) ?>
				<span id="chap"></span>
				<input type="image" src="/images/join.png" alt="Join" id="joinbutton" style="display: none; margin-left: 399px; margin-top: 5px;">
			</form>
		</div>
	</div>
	
	<div class="vspacer20">&nbsp;</div>
</div>

<script type="text/javascript">
	function addview(ele){
		eleh = ele+"h";
		document.getElementById(document.getElementById('curadd').value+"h").style.backgroundColor = '#D8D2BD';
		document.getElementById(eleh).style.backgroundColor = '#D5DEFB';
		document.getElementById(document.getElementById('curadd').value).style.display = 'none';
		document.getElementById(ele).style.display = 'block';
		
		document.getElementById('curadd').value = ele;
	}
	
	function getchapters(regionid){
		var url = "/address/getchapters.html";
		var param = "rid="+regionid;
		new Ajax.Updater('chap', url, {method: 'get', parameters: param,onComplete:function() {
			}});
		if((regionid == 0) || (document.getElementById('chapter').value != 0)){
			document.getElementById('joinbutton').style.display = 'none';
		}
	}

	function getsubmit(){
		if(document.getElementById('chapter').value != 0){
			document.getElementById('joinbutton').style.display = 'block';
		}else{
			document.getElementById('joinbutton').style.display = 'none';
		}
	}
	
	function delchap(crid, chapname){
		if(confirm("Do you want to UNJOIN from "+chapname+" ??")){
			location.href = "/address/unjoinchapter/crid/"+crid+".html";
		}
	}

</script>
