<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:52
?>
<h1>chapter</h1>

<table>
<thead>
<tr>
  <th>Chapter</th>
  <th>Region</th>
</tr>
</thead>
<tbody>
<?php foreach ($chapters as $chapter): ?>
<tr>
      <td><?php echo $chapter->getName() ?></td>
      <td><?php echo $chapter->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'chapter/create') ?>
