<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:17:52
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $chapter->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $chapter->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'chapter/edit?id='.$chapter->getId()) ?>
&nbsp;<?php echo link_to('list', 'chapter/list') ?>
