<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:52:55
?>
<?php use_helper('Object') ?>

<?php echo form_tag('involvement/update') ?>

<?php echo object_input_hidden_tag($involvement, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($involvement, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($involvement->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'involvement/delete?id='.$involvement->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'involvement/show?id='.$involvement->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'involvement/list') ?>
<?php endif; ?>
</form>
