<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:19:38
?>
<?php

/**
 * hobbies actions.
 *
 * @package    sf_sandbox
 * @subpackage hobbies
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class hobbiesActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('hobbies', 'list');
  }

  public function executeList()
  {
    $this->hobbiess = HobbiesPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->hobbies = HobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->hobbies);
  }

  public function executeCreate()
  {
    $this->hobbies = new Hobbies();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->hobbies = HobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->hobbies);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $hobbies = new Hobbies();
    }
    else
    {
      $hobbies = HobbiesPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($hobbies);
    }

    $hobbies->setId($this->getRequestParameter('id'));
    $hobbies->setName($this->getRequestParameter('name'));

    $hobbies->save();

    return $this->redirect('hobbies/show?id='.$hobbies->getId());
  }

  public function executeDelete()
  {
    $hobbies = HobbiesPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($hobbies);

    $hobbies->delete();

    return $this->redirect('hobbies/list');
  }
}
