<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:18:10
?>
<?php

/**
 * region actions.
 *
 * @package    sf_sandbox
 * @subpackage region
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class regionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('region', 'list');
  }

  public function executeList()
  {
    $this->regions = RegionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->region = RegionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->region);
  }

  public function executeCreate()
  {
    $this->region = new Region();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->region = RegionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->region);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $region = new Region();
    }
    else
    {
      $region = RegionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($region);
    }

    $region->setId($this->getRequestParameter('id'));
    $region->setName($this->getRequestParameter('name'));

    $region->save();

    return $this->redirect('region/show?id='.$region->getId());
  }

  public function executeDelete()
  {
    $region = RegionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($region);

    $region->delete();

    return $this->redirect('region/list');
  }
}
