<?php
// auto-generated by sfPropelCrud
// date: 2009/07/17 06:53:53
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $news->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $news->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'news/edit?id='.$news->getId()) ?>
&nbsp;<?php echo link_to('list', 'news/list') ?>
