<?php include_component('home','leftmenu'); ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:08
?>
<?php use_helper('Object') ?>

<?php echo form_tag('personal/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($personal, 'getId') ?>

<input type="hidden" name="user_id" value="<?php echo $personal->getUserId(); ?>">

<table width="100%" class="profiletable">
<tbody>
<tr class="oddRow">
  <th>Image:</th>
  <td><?php echo input_file_tag('image', array('size'=>'30')); ?></td>
  <td>&nbsp;</td>
</tr>
<tr class="evenRow">
  <th>Salutation:</th>
  <td><?php echo object_input_tag($personal, 'getSalutation', array (
  'size' => 5,
)) ?></td>
<td>&nbsp;</td>
</tr>
<tr class="oddRow">
  <th>Firstname:</th>
  <td><?php echo object_input_tag($personal, 'getFirstname', array (
  'size' => 30,
)) ?></td>
<td>&nbsp;</td>
</tr>
<tr class="evenRow">
  <th>Middlename:</th>
  <td><?php echo object_input_tag($personal, 'getMiddlename', array (
  'size' => 30,
)) ?></td>
<td>&nbsp;</td>
</tr>
<tr class="oddRow">
  <th>Lastname:</th>
  <td><?php echo object_input_tag($personal, 'getLastname', array (
  'size' => 30,
)) ?></td>
<td>&nbsp;</td>
</tr>
<tr class="evenRow">
  <th>Maidenname:</th>
  <td><?php echo object_input_tag($personal, 'getMaidenname', array (
  'size' => 30,
)) ?></td>
<td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('maidennameflag', options_for_select($privacyoptions, $personal->getMaidennameflag())) ?>
</td>
</tr>
<tr class="oddRow">
  <th>Itbhuname:</th>
  <td><?php echo object_input_tag($personal, 'getItbhuname', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
	<?php echo select_tag('itbhunameflag', options_for_select($privacyoptions, $personal->getItbhunameflag())) ?>
  </td>
</tr>
<tr class="evenRow">
  <th>Gender:</th>
  <td><?php echo object_input_tag($personal, 'getGender', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('genderflag', options_for_select($privacyoptions, $personal->getGenderflag())) ?>
  </td>
</tr>
<tr class="oddRow">
  <th>Dob:</th>
  <td><?php echo object_input_date_tag($personal, 'getDob', array (
  'rich' => true,
  'withtime' => false,
  'size' => 30,
  )) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('dobflag', options_for_select($privacyoptions, $personal->getDobflag())) ?>
  </td>
</tr>
<tr class="evenRow">
  <th>Maritalstatus:</th>
  <td><?php echo object_input_tag($personal, 'getMaritalstatus', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('maritalstatusflag', options_for_select($privacyoptions, $personal->getMaritalstatusflag())) ?>
  </td>
</tr>
<tr class="oddRow">
  <th>Email:</th>
  <td><?php echo object_input_tag($personal, 'getEmail', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('emailflag', options_for_select($privacyoptions, $personal->getEmailflag())) ?>
  </td>
</tr>
<tr class="evenRow">
  <th>Website:</th>
  <td><?php echo object_input_tag($personal, 'getWebsite', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('websiteflag', options_for_select($privacyoptions, $personal->getWebsiteflag())) ?>
  </td>
</tr>
<tr class="oddRow">
  <th>Linkedin:</th>
  <td><?php echo object_input_tag($personal, 'getLinkedin', array (
  'size' => 30,
)) ?></td>
  <td>
  	<div style="float: left;"><img src="/images/privacy.jpg" width="28px;" height="24px;" /></div>
  	<?php echo select_tag('linkedinflag', options_for_select($privacyoptions, $personal->getLinkedinflag())) ?>
  </td>
</tr>
</tbody>
</table>
<hr />

<?php /*
   echo textarea_tag('itemname','',array(
	'rich' => 'fck',
	'height' => 295,
	'width'	=> 770,'class' => 'descclass'

   )); 
    $contenttext = $this->getRequestParameter('itemname');
  	if(strpos($contenttext,'<p>')>=0){

			$contenttext=str_replace('<p>','',$contenttext);
			$contenttext=str_replace('</p>','<br/>',$contenttext);
		}
    $personal->setLinkedin($contenttext);
*/ ?>


<?php echo submit_tag('Save') ?>
<?php if ($personal->getId()): ?>
  &nbsp;<?php echo button_to('Cancel', 'personal/show?id='.$personal->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo button_to('cancel', 'personal/list') ?>
<?php endif; ?>
</form>
