<?php
// auto-generated by sfPropelCrud
// date: 2009/02/10 08:16:08
?>
<h1>personal</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Image</th>
  <th>Imageflag</th>
  <th>Salutation</th>
  <th>Firstname</th>
  <th>Firstnameflag</th>
  <th>Middlename</th>
  <th>Middlenameflag</th>
  <th>Lastname</th>
  <th>Lastnameflag</th>
  <th>Maidenname</th>
  <th>Maidennameflag</th>
  <th>Itbhuname</th>
  <th>Itbhunameflag</th>
  <th>Gender</th>
  <th>Genderflag</th>
  <th>Dob</th>
  <th>Dobflag</th>
  <th>Maritalstatus</th>
  <th>Maritalstatusflag</th>
  <th>Email</th>
  <th>Emailflag</th>
  <th>Website</th>
  <th>Websiteflag</th>
  <th>Linkedin</th>
  <th>Linkedinflag</th>
</tr>
</thead>
<tbody>
<?php foreach ($personals as $personal): ?>
<tr>
    <td><?php echo link_to($personal->getId(), 'personal/show?id='.$personal->getId()) ?></td>
      <td><?php echo $personal->getUserId() ?></td>
      <td><?php echo $personal->getImage() ?></td>
      <td><?php echo $personal->getImageflag() ?></td>
      <td><?php echo $personal->getSalutation() ?></td>
      <td><?php echo $personal->getFirstname() ?></td>
      <td><?php echo $personal->getFirstnameflag() ?></td>
      <td><?php echo $personal->getMiddlename() ?></td>
      <td><?php echo $personal->getMiddlenameflag() ?></td>
      <td><?php echo $personal->getLastname() ?></td>
      <td><?php echo $personal->getLastnameflag() ?></td>
      <td><?php echo $personal->getMaidenname() ?></td>
      <td><?php echo $personal->getMaidennameflag() ?></td>
      <td><?php echo $personal->getItbhuname() ?></td>
      <td><?php echo $personal->getItbhunameflag() ?></td>
      <td><?php echo $personal->getGender() ?></td>
      <td><?php echo $personal->getGenderflag() ?></td>
      <td><?php echo $personal->getDob() ?></td>
      <td><?php echo $personal->getDobflag() ?></td>
      <td><?php echo $personal->getMaritalstatus() ?></td>
      <td><?php echo $personal->getMaritalstatusflag() ?></td>
      <td><?php echo $personal->getEmail() ?></td>
      <td><?php echo $personal->getEmailflag() ?></td>
      <td><?php echo $personal->getWebsite() ?></td>
      <td><?php echo $personal->getWebsiteflag() ?></td>
      <td><?php echo $personal->getLinkedin() ?></td>
      <td><?php echo $personal->getLinkedinflag() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'personal/create') ?>
